# This workflow generates documentation with Doxygen and publishes it to GitHub Pages.
name: Deploy Documentation

# Controls when the action will run.
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare Doxygen output directory
        run: mkdir -p docs/doxygen
      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@v1.2.1
        with:
          doxyfile-path: ./Doxyfile
          working-directory: .
      - name: Pages Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/doxygen/html/
          enable_jekyll: false
          allow_empty_commit: false
          force_orphan: true
          publish_branch: github-pages
